apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clae-nivenly
spec:
  serviceName: clae-nivenly
  selector:
    matchLabels:
      app: clae-nivenly
  template:
    metadata:
      labels:
        app: clae-nivenly
    spec:
      hostNetwork: true
      volumes:
      - name: clae-sqlite
        hostPath:
          path: /data/clae
      containers:
      - name: clae
        imagePullPolicy: Always
        image: ghcr.io/nivenly/clae:main
        env:
          - name: DATABASE
            value: /sqlite/nivenly-clae.db
          - name: LISTEN
            value: ":30036"
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: clae-nivenly-token
                key: TOKEN
                optional: false
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30036
          name: clae-nivenly
        volumeMounts:
          - mountPath: /sqlite
            name: clae-nivenly-pvc
  volumeClaimTemplates:
  - metadata:
      name: clae-nivenly-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: do-block-storage
